name: scikit-learn Clustering Example

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'sklearn-clustering-simple/**'

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Upload dataset
        id: dataset
        uses: PIpedream-in/upload-dataset@v1
        with:
          api-key: ${{ secrets.PDTRAIN_API_KEY }}
          api-url: https://6c68b9fad00b.ngrok-free.app
          path: ./sklearn-clustering-simple/data
          name: sklearn-data-${{ github.run_number }}
          description: scikit-learn clustering dataset

      - name: Run K-Means Clustering
        id: train
        uses: PIpedream-in/train-ml@v1
        with:
          api-key: ${{ secrets.PDTRAIN_API_KEY }}
          code-path: ./sklearn-clustering-simple
          entry-point: train.py
          dataset: ${{ steps.dataset.outputs.dataset-id }}
          framework: sklearn
          framework-version: 1.4.2
          python-version: py310
          hyperparameters: |
            n_clusters: 3
            max_iter: 100

      - name: Show results
        run: |
          echo "## scikit-learn Clustering Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Run ID:** \`${{ steps.train.outputs.run-id }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **Status:** ${{ steps.train.outputs.status }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Cost:** \$${{ steps.train.outputs.cost }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Runtime:** ${{ steps.train.outputs.runtime-seconds }}s" >> $GITHUB_STEP_SUMMARY

