name: TensorFlow Training Example

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'tensorflow-regression-simple/**'

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Upload dataset
        id: dataset
        uses: PIpedream-in/upload-dataset-action@v1
        with:
          api-key: ${{ secrets.PDTRAIN_API_KEY }}
          api-url: https://6c68b9fad00b.ngrok-free.app
          path: ./tensorflow-regression-simple/data
          name: tensorflow-data-${{ github.run_number }}
          description: TensorFlow regression dataset

      - name: Train TensorFlow Model
        id: train
        uses: PIpedream-in/train-ml-action@v1
        with:
          api-key: ${{ secrets.PDTRAIN_API_KEY }}
          api-url: https://6c68b9fad00b.ngrok-free.app
          code-path: ./tensorflow-regression-simple
          entry-point: train.py
          dataset: ${{ steps.dataset.outputs.dataset-id }}
          framework: tensorflow
          framework-version: 2.13.0
          download-artifacts: false
          exclude-patterns: data/
          python-version: py310
          hyperparameters: |
            epochs: 3
            batch_size: 32
            learning_rate: 0.001

      - name: Show results
        run: |
          echo "## TensorFlow Training Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Run ID:** \`${{ steps.train.outputs.run-id }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **Status:** ${{ steps.train.outputs.status }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Cost:** \$${{ steps.train.outputs.cost }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Runtime:** ${{ steps.train.outputs.runtime-seconds }}s" >> $GITHUB_STEP_SUMMARY

